cadvisor:
  image:
    repository: gcr.io/cadvisor/cadvisor
    tag: v0.49.1
  # Resources are required to set to avoid opening too many files error for example
  resources:
    requests:
      cpu: 400m
      memory: 400Mi
    limits:
      cpu: 800m
      memory: 2000Mi
  service:
    port: 8080
    targetPort: 8080
prometheus:
  rbac:
    enabled: true